# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190130_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signfeedback',
            name='isAuslan',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'Perhaps'), (3, "Don't know"), (4, "Don't think so"), (5, 'No'), (0, 'N/A')], verbose_name='Is this sign an Português Brasileiro Sign?'),
        ),
    ]
