# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20190208_1841'),
        ('feedback', '0003_auto_20190212_1550'),
    ]

    operations = [
    ]
