# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_glossvideo_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='videofile',
            field=models.FileField(upload_to=signbank.video.models.sinal_upload_path, verbose_name='video file'),
        ),
    ]
