# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_auto_20180328_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Localização')),
                ('localimage', models.FileField(upload_to='localimage', verbose_name='Imagem')),
            ],
            options={
                'verbose_name_plural': 'Localizations',
                'verbose_name': 'Localization',
            },
        ),
        # migrations.AddField(
        #     model_name='language',
        #     name='name_pt_br',
        #     field=models.CharField(max_length=50, null=True),
        # ),
        migrations.AlterField(
            model_name='deletedglossormedia',
            name='annotation_idgloss',
            field=models.CharField(max_length=30, verbose_name='Annotation ID Gloss'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='contType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='dataset',
            field=models.ForeignKey(help_text='Dataset a gloss is part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dataset', verbose_name='Dataset'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='derivHist',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=50, verbose_name='Derivation history'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh_letter',
            field=models.NullBooleanField(verbose_name='Strong hand letter'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh_number',
            field=models.NullBooleanField(verbose_name='Strong hand number'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Final Dominant Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_loc',
            field=models.IntegerField(blank=True, choices=[('0', '-'), ('1', 'N/A')], null=True, verbose_name='Final Primary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_secondary_loc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=20, null=True, verbose_name='Final Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handCh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Handshape Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handedness',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('2', 'X')], max_length=5, null=True, verbose_name='Handedness'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='initial_secondary_loc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=20, null=True, verbose_name='Initial Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locPrimLH',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Placement Active Articulator LH'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locprim',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locsecond',
            field=models.IntegerField(blank=True, choices=[('0', '-'), ('1', 'N/A')], null=True, verbose_name='Secondary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movDir',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Movement Direction'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movSh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Movement Shape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='namEnt',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Named Entity'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='oriCh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Orientation Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriLoc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Relative Orientation: Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriMov',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Relative Orientation: Movement'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relatArtic',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Relation between Articulators'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='semField',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Semantic Field'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Weak Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh_letter',
            field=models.NullBooleanField(verbose_name='Weak hand letter'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh_number',
            field=models.NullBooleanField(verbose_name='Weak hand number'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='valence',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=50, null=True, verbose_name='Valence'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='weakdrop',
            field=models.NullBooleanField(verbose_name='Weak Drop'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='weakprop',
            field=models.NullBooleanField(verbose_name='Weak Prop'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='wordClass',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Word class'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='wordClass2',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Word class 2'),
        ),
        migrations.AlterField(
            model_name='morpheme',
            name='mrpType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='morphologydefinition',
            name='role',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], max_length=5),
        ),
        migrations.AlterField(
            model_name='othermedia',
            name='type',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_used_language',
            field=models.CharField(default='pt', max_length=20),
        ),
        migrations.AddField(
            model_name='gloss',
            name='localization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Localization', verbose_name='Localização'),
        ),
    ]
