# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0022_auto_20190212_1739_squashed_0024_auto_20190212_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='imagem',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gloss',
            name='localizacao',
            field=models.CharField(choices=[('testa', 'Testa'), ('olhos_nariz', 'Olhos e Nariz'), ('boca_queixo', 'Boca e Queixo'), ('pescoco', 'Pescoço'), ('ombro', 'Ombro'), ('bracos', 'Braços'), ('pernas', 'Pernas'), ('espaco_neutro', 'Espaço Neutro'), ('tronco', 'Tronco')], max_length=15, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_used_language',
            field=models.CharField(default='pt-br', max_length=20),
        ),
    ]
