# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0023_auto_20190130_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='localization',
            field=models.CharField(choices=[('F1', 'Face 1 - Testa'), ('F2', 'Face 2 - Olhos e Nariz'), ('F3', 'Face 3 - Boca e Queixo'), ('F4', 'Face 4 - Pescoço'), ('O', 'Ombro'), ('B', 'Braços'), ('P', 'Pernas'), ('EN', 'Espaço Neutro'), ('T', 'Tronco')], max_length=2, null=True, verbose_name='Localização'),
        ),
        migrations.DeleteModel(
            name='Localization',
        ),
    ]
