# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_auto_20190130_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='localization',
            field=models.CharField(choices=[('testa', 'Testa'), ('ohos_nariz', 'Olhos e Nariz'), ('boca_queixo', 'Boca e Queixo'), ('pescoco', 'Pescoço'), ('ombro', 'Ombro'), ('bracos', 'Braços'), ('pernas', 'Pernas'), ('espaco_neutro', 'Espaço Neutro'), ('tronco', 'Tronco')], max_length=15, null=True, verbose_name='Localização'),
        ),
    ]
