# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_auto_20190130_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gloss',
            old_name='localization',
            new_name='localizacao',
        ),
    ]
