# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0027_auto_20190205_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_used_language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
