# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_auto_20190208_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='traducao_ingles',
            field=models.CharField(max_length=50, null=True, verbose_name='Tradução Inglês'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_used_language',
            field=models.CharField(default='pt-br', max_length=20),
        ),
    ]
