# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0029_auto_20190208_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gloss',
            name='nome_sinal',
        ),
        migrations.RemoveField(
            model_name='gloss',
            name='traducao_ingles',
        ),
    ]
