# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0030_auto_20190208_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='imagem',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
