# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0026_auto_20190220_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Final Dominant Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handedness',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Handedness'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Weak Hand'),
        ),
    ]
