# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-20 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0029_auto_20200921_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm',
            options={'verbose_name': 'Configuração de Mão', 'verbose_name_plural': 'Configurações de Mão'},
        ),
        migrations.AlterModelOptions(
            name='localization',
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
    ]
