# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0032_auto_20200927_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='handednessgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem grupo número de mãos'),
        ),
    ]
