# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0033_handednessgroup_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handshape',
            options={'verbose_name': 'Configuração de mão', 'verbose_name_plural': 'Configurações de Mão'},
        ),
        migrations.AlterModelOptions(
            name='handshapegroup',
            options={'verbose_name': 'Grupo de configuração de Mão', 'verbose_name_plural': 'Grupo de configurações de Mão'},
        ),
        migrations.AddField(
            model_name='gloss',
            name='basehndsh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_handshape', to='dictionary.Handshape', verbose_name='Configuração de mão - Mão base'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='hands_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Handedness', verbose_name=''),
        ),
        migrations.AddField(
            model_name='gloss',
            name='mainhndsh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dominant_handshape', to='dictionary.Handshape', verbose_name='Configuração de mão - Mão dominante'),
        ),
    ]
