# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-29 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0035_auto_20200927_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handshapegroup',
            options={'verbose_name': 'Grupo de configuração de Mão', 'verbose_name_plural': 'Grupos de configurações de Mão'},
        ),
    ]
