# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0037_auto_20200930_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='localization',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Localização Slug Name'),
        ),
    ]
