# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0038_localization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('135', '1'), ('136', '1_curved'), ('137', "1' - e - [Libras_7]"), ('138', '3'), ('139', '4'), ('140', '4_V'), ('141', '5'), ('142', '5_claw'), ('143', '5i'), ('144', '5_lax'), ('145', '5m'), ('146', '5m_closed'), ('147', '5m_open'), ('148', '5mr'), ('149', '5mr_closed'), ('150', '5mr_closed'), ('151', '5r'), ('152', '5r_closed'), ('153', '9'), ('154', 'A'), ('155', 'A_open'), ('157', '[ASL_T]'), ('158', 'B'), ('159', 'B1'), ('160', 'B2'), ('161', 'B+1'), ('162', 'Baby_beak'), ('163', 'Baby_beak_open'), ('164', 'Baby_C'), ('165', 'Baby_C_extended'), ('166', 'Baby_O'), ('167', 'Baby_O2'), ('168', 'B_bent'), ('169', 'B_bent1'), ('170', 'B_curved'), ('171', 'B_curved1'), ('172', 'Beak'), ('173', 'Beak2'), ('174', 'Beak2_open'), ('175', 'Beak2_open_spread'), ('176', 'Beak_open'), ('177', 'Beak_open1'), ('178', 'Beak_open_spread'), ('179', 'C'), ('180', 'D'), ('181', 'E'), ('182', 'F[Libras_T]'), ('183', 'Flower'), ('184', 'G'), ('185', 'Horns'), ('186', 'Horns_curved'), ('187', 'i'), ('188', 'i_curved'), ('189', 'iLY'), ('190', 'K'), ('191', 'Key'), ('192', 'L'), ('193', 'L2'), ('194', 'L2_twist'), ('195', 'L_curved'), ('196', '[Libras_6]'), ('197', '[Libras_9]'), ('198', '[Libras_A]'), ('199', '[Libras_F]'), ('200', '[Libras_P]'), ('201', 'M'), ('202', 'Money'), ('203', 'N'), ('204', 'O'), ('205', 'P'), ('206', 'Q'), ('207', 'R'), ('208', 'R_open'), ('209', 'S'), ('210', 'T[ASL_F]'), ('211', 'T closed[ASL F]'), ('212', 'T_open[ASL_F]'), ('213', 'U'), ('214', 'V'), ('215', 'V_curved'), ('216', 'W'), ('217', 'W_curved'), ('219', 'Y')], max_length=5, null=True, verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('135', '1'), ('136', '1_curved'), ('137', "1' - e - [Libras_7]"), ('138', '3'), ('139', '4'), ('140', '4_V'), ('141', '5'), ('142', '5_claw'), ('143', '5i'), ('144', '5_lax'), ('145', '5m'), ('146', '5m_closed'), ('147', '5m_open'), ('148', '5mr'), ('149', '5mr_closed'), ('150', '5mr_closed'), ('151', '5r'), ('152', '5r_closed'), ('153', '9'), ('154', 'A'), ('155', 'A_open'), ('157', '[ASL_T]'), ('158', 'B'), ('159', 'B1'), ('160', 'B2'), ('161', 'B+1'), ('162', 'Baby_beak'), ('163', 'Baby_beak_open'), ('164', 'Baby_C'), ('165', 'Baby_C_extended'), ('166', 'Baby_O'), ('167', 'Baby_O2'), ('168', 'B_bent'), ('169', 'B_bent1'), ('170', 'B_curved'), ('171', 'B_curved1'), ('172', 'Beak'), ('173', 'Beak2'), ('174', 'Beak2_open'), ('175', 'Beak2_open_spread'), ('176', 'Beak_open'), ('177', 'Beak_open1'), ('178', 'Beak_open_spread'), ('179', 'C'), ('180', 'D'), ('181', 'E'), ('182', 'F[Libras_T]'), ('183', 'Flower'), ('184', 'G'), ('185', 'Horns'), ('186', 'Horns_curved'), ('187', 'i'), ('188', 'i_curved'), ('189', 'iLY'), ('190', 'K'), ('191', 'Key'), ('192', 'L'), ('193', 'L2'), ('194', 'L2_twist'), ('195', 'L_curved'), ('196', '[Libras_6]'), ('197', '[Libras_9]'), ('198', '[Libras_A]'), ('199', '[Libras_F]'), ('200', '[Libras_P]'), ('201', 'M'), ('202', 'Money'), ('203', 'N'), ('204', 'O'), ('205', 'P'), ('206', 'Q'), ('207', 'R'), ('208', 'R_open'), ('209', 'S'), ('210', 'T[ASL_F]'), ('211', 'T closed[ASL F]'), ('212', 'T_open[ASL_F]'), ('213', 'U'), ('214', 'V'), ('215', 'V_curved'), ('216', 'W'), ('217', 'W_curved'), ('219', 'Y')], max_length=5, null=True, verbose_name='Final Dominant Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('135', '1'), ('136', '1_curved'), ('137', "1' - e - [Libras_7]"), ('138', '3'), ('139', '4'), ('140', '4_V'), ('141', '5'), ('142', '5_claw'), ('143', '5i'), ('144', '5_lax'), ('145', '5m'), ('146', '5m_closed'), ('147', '5m_open'), ('148', '5mr'), ('149', '5mr_closed'), ('150', '5mr_closed'), ('151', '5r'), ('152', '5r_closed'), ('153', '9'), ('154', 'A'), ('155', 'A_open'), ('157', '[ASL_T]'), ('158', 'B'), ('159', 'B1'), ('160', 'B2'), ('161', 'B+1'), ('162', 'Baby_beak'), ('163', 'Baby_beak_open'), ('164', 'Baby_C'), ('165', 'Baby_C_extended'), ('166', 'Baby_O'), ('167', 'Baby_O2'), ('168', 'B_bent'), ('169', 'B_bent1'), ('170', 'B_curved'), ('171', 'B_curved1'), ('172', 'Beak'), ('173', 'Beak2'), ('174', 'Beak2_open'), ('175', 'Beak2_open_spread'), ('176', 'Beak_open'), ('177', 'Beak_open1'), ('178', 'Beak_open_spread'), ('179', 'C'), ('180', 'D'), ('181', 'E'), ('182', 'F[Libras_T]'), ('183', 'Flower'), ('184', 'G'), ('185', 'Horns'), ('186', 'Horns_curved'), ('187', 'i'), ('188', 'i_curved'), ('189', 'iLY'), ('190', 'K'), ('191', 'Key'), ('192', 'L'), ('193', 'L2'), ('194', 'L2_twist'), ('195', 'L_curved'), ('196', '[Libras_6]'), ('197', '[Libras_9]'), ('198', '[Libras_A]'), ('199', '[Libras_F]'), ('200', '[Libras_P]'), ('201', 'M'), ('202', 'Money'), ('203', 'N'), ('204', 'O'), ('205', 'P'), ('206', 'Q'), ('207', 'R'), ('208', 'R_open'), ('209', 'S'), ('210', 'T[ASL_F]'), ('211', 'T closed[ASL F]'), ('212', 'T_open[ASL_F]'), ('213', 'U'), ('214', 'V'), ('215', 'V_curved'), ('216', 'W'), ('217', 'W_curved'), ('219', 'Y')], max_length=5, null=True, verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='hands_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Handedness', verbose_name='Número de Mãos'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('135', '1'), ('136', '1_curved'), ('137', "1' - e - [Libras_7]"), ('138', '3'), ('139', '4'), ('140', '4_V'), ('141', '5'), ('142', '5_claw'), ('143', '5i'), ('144', '5_lax'), ('145', '5m'), ('146', '5m_closed'), ('147', '5m_open'), ('148', '5mr'), ('149', '5mr_closed'), ('150', '5mr_closed'), ('151', '5r'), ('152', '5r_closed'), ('153', '9'), ('154', 'A'), ('155', 'A_open'), ('157', '[ASL_T]'), ('158', 'B'), ('159', 'B1'), ('160', 'B2'), ('161', 'B+1'), ('162', 'Baby_beak'), ('163', 'Baby_beak_open'), ('164', 'Baby_C'), ('165', 'Baby_C_extended'), ('166', 'Baby_O'), ('167', 'Baby_O2'), ('168', 'B_bent'), ('169', 'B_bent1'), ('170', 'B_curved'), ('171', 'B_curved1'), ('172', 'Beak'), ('173', 'Beak2'), ('174', 'Beak2_open'), ('175', 'Beak2_open_spread'), ('176', 'Beak_open'), ('177', 'Beak_open1'), ('178', 'Beak_open_spread'), ('179', 'C'), ('180', 'D'), ('181', 'E'), ('182', 'F[Libras_T]'), ('183', 'Flower'), ('184', 'G'), ('185', 'Horns'), ('186', 'Horns_curved'), ('187', 'i'), ('188', 'i_curved'), ('189', 'iLY'), ('190', 'K'), ('191', 'Key'), ('192', 'L'), ('193', 'L2'), ('194', 'L2_twist'), ('195', 'L_curved'), ('196', '[Libras_6]'), ('197', '[Libras_9]'), ('198', '[Libras_A]'), ('199', '[Libras_F]'), ('200', '[Libras_P]'), ('201', 'M'), ('202', 'Money'), ('203', 'N'), ('204', 'O'), ('205', 'P'), ('206', 'Q'), ('207', 'R'), ('208', 'R_open'), ('209', 'S'), ('210', 'T[ASL_F]'), ('211', 'T closed[ASL F]'), ('212', 'T_open[ASL_F]'), ('213', 'U'), ('214', 'V'), ('215', 'V_curved'), ('216', 'W'), ('217', 'W_curved'), ('219', 'Y')], max_length=5, null=True, verbose_name='Weak Hand'),
        ),
    ]
