# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-19 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170323_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossvideo',
            name='version',
        ),
    ]
